---
# defaults file for provision/roles/nc-gluster-run

gluster_cluster_hosts:
  - glnode1
  - glnode2

gluster_brick_dir: /srv/gluster/brick
gluster_brick_vol: /srv/gluster/brick/gv0
gluster_brick_name: gv0

