Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-stream-8"
    config.vm.define "server" do |server|
    server.vm.hostname = "server.loc"
    server.vm.network "private_network", ip: "192.168.56.10"
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/provision.yml"
        ansible.become = "true"
    end
    end