version: '3.3'
services:
  webserver:
      build: ./nginx
      ports:
          - "80:80"
      networks:
          - front
      volumes:
          - ./php:/code

  tomcatserver:
      build: ./tomcat
      command: catalina.sh run
      ports:
        - "8080:8080"
      networks:
          - front

  goserver:
      build: ./go
      ports:
          - "8081:8081"
      networks:
          - front

  rubyserver:
      build: ./ruby
      ports:
          - "8082:8082"
      networks:
          - front

networks:
  front: