---
# tasks file for provision/roles/nc-netdata-slave

- name: install IUS repo
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present

- name: remove conficting packages
  yum:
    name: git
    state: absent

- name: installing prerequisites packages
  yum:
    name: "{{ netdata_pre_reqs }}"
    state: present

- name: clone {{ netdata_git_repo }} to {{ netdata_source_dir }}
  git:
    repo: "{{ netdata_git_repo }}"
    dest: "{{ netdata_source_dir }}"
    depth: 1

- name: install netdata
  command: "{{ netdata_installer }} --dont-wait"
  args:
    chdir: "{{ netdata_source_dir }}"
    creates: /usr/sbin/netdata

- name: copy netdata.conf
  template:
    src: netdata.conf.j2
    dest: "{{ netdata_config_file }}"
    owner: "netdata"
    group: root
    mode: 0644

- name: copy stream.conf
  template:
    src: stream.conf.j2
    dest: "{{ netdata_stream_config_file }}"
    owner: "netdata"
    group: root
    mode: 0644
  notify: restart netdata
