- name: Postgres
  hosts: all
  become: yes
  tasks:
  #Устанавливаем vim и telnet (для более удобной работы с хостами)
  - name: install base tools
    dnf:
      name:
        - vim
        - telnet
      state: present
      update_cache: true

#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: install postgres 14 and set up replication
  hosts: node1,node2
  become: yes
  roles:
   - install_postgres
   - postgres_replication

#Запуск роли install_barman на всех хостах
- name: set up backup
  hosts: all
  become: yes
  roles:
   - install_barman

# Отключаем firewalld и удаляем его из автозагрузки
- name: disable firewalld service
  service:
      name: firewalld
      state: stopped
      enabled: false
  
# Отключаем SElinux 
- name: Disable SELinux
  selinux:
      state: disabled
  
# Отключаем SElinux после перезагрузки
- name: Ensure SELinux is set to disable mode
  lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled

# Добавляем репозиторий postgres
- name: install repo
  dnf:
      name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
      state: present
  
# Отключаем старый модуль
- name: disable old postgresql module
  shell: dnf -qy module disable postgresql

# Устанавливаем postgresql14-server
- name: install postgresql-server 14
  dnf: 
      name: postgresql14-server
      state: present
      update_cache: true

# Проверяем, что postgres на хосте ещё не инициализирован
- name: check init 
  stat:
      path: /var/lib/pgsql/14/data/pg_stat
  register: stat_result

# Выполняем инициализацию postgres
- name: initialization setup
  shell: sudo /usr/pgsql-14/bin/postgresql-14-setup initdb
  when: not stat_result.stat.exists
  
# Запускаем postgresql-14
- name: enable and start service
  service:
      name: postgresql-14
      state: started
      enabled: true
