---
- name: prepare OS
  hosts: all
  become: yes
  roles:
    - nc-os
    - nc-firewalld

- name: setup netdata-master
  hosts: mon
  become: yes
  roles:
    - nc-netdata-master
    - nc-pmm-server
    - nc-backup-user
    - nc-rsyslog-server

- name: prepare InnoDB Cluster nodes
  hosts:
    - sqlnode1
    - sqlnode2
    - sqlnode3
  become: yes
  roles:
    - icluster-node
    #    - nc-netdata-slave
    - nc-pmm-client
    - nc-rsyslog-sender

- name: prepare GlusterFS nodes
  hosts:
    - glnode1
    - glnode2
  become: yes
  roles:
    - nc-gluster-infra
    - nc-gluster-setup
    - nc-netdata-slave
    - nc-rsyslog-sender

- name: setup GlusterFS
  hosts: glnode2
  become: yes
  roles:
    - nc-gluster-run

- name: setup InnoDB Cluster
  hosts: backend1
  become: yes
  roles:
    - icluster-setup

- name: setup MySQL Routers
  hosts:
    - backend1
    - backend2
  become: yes
  roles:
    - icluster-router
    - nc-rsyslog-sender

- name: setup backend1
  hosts: backend1
  become: yes
  roles:
    - nc-gluster-client
    - nc-nginx
    #    - nc-netdata-slave
    - nc-backup-user
    - nc-restic
    - nc-redis
    - nc-php
    - nc-mysql

- name: install nextcloud app
  hosts: backend1
  become: yes
  roles:
    - nc-app

- name: setup backend2
  hosts: backend2
  become: yes
  roles:
    - nc-gluster-client
    - nc-nginx
    #    - nc-netdata-slave
    - nc-redis
    - nc-php

- name: setup haproxies
  hosts:
    - haproxy1
    - haproxy2
  become: yes
  roles:
    - nc-gluster-client
    - nc-ssl
    - nc-haproxy
    #    - nc-netdata-slave
    - nc-rsyslog-sender

- name: setup keepalived
  hosts:
    - haproxy1
    - haproxy2
  become: yes
  roles:
    - nc-keepalived

